language: generic
sudo: required

services: 
  - docker

before_install:
  - docker build -t swipped/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true swipped/docker-react npm run test