language: generic
sudo: required

services: 
  - docker

before_install:
  - docker build -t emirxxx/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true emirxxx/docker-react npm run test -- --coverage